---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: service-ui
  namespace: flux-system
spec:
  interval: 2m0s
  releaseName: service-ui
  targetNamespace: service-ui
  install:
    createNamespace: true
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "19.0.0"
  values:
    replicaCount: 2
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    ingress:
      enabled: true
      ingressClassName: cloudflare-tunnel
      hostname: demo.mhcp001.uk

