repositories:
  - name: strrl.dev
    url: https://helm.strrl.dev

releases:
  - name: cloudlared-ingress-controller
    namespace: cloudflared
    chart: strrl.dev/cloudflare-tunnel-ingress-controller
